// Generated by gencpp from file arm_control_tcp/ClearErrorResponse.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_TCP_MESSAGE_CLEARERRORRESPONSE_H
#define ARM_CONTROL_TCP_MESSAGE_CLEARERRORRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control_tcp
{
template <class ContainerAllocator>
struct ClearErrorResponse_
{
  typedef ClearErrorResponse_<ContainerAllocator> Type;

  ClearErrorResponse_()
    : res(0)  {
    }
  ClearErrorResponse_(const ContainerAllocator& _alloc)
    : res(0)  {
  (void)_alloc;
    }



   typedef int32_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ClearErrorResponse_

typedef ::arm_control_tcp::ClearErrorResponse_<std::allocator<void> > ClearErrorResponse;

typedef boost::shared_ptr< ::arm_control_tcp::ClearErrorResponse > ClearErrorResponsePtr;
typedef boost::shared_ptr< ::arm_control_tcp::ClearErrorResponse const> ClearErrorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator1> & lhs, const ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator1> & lhs, const ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_control_tcp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca16cfbd5443ad97ULL;
  static const uint64_t static_value2 = 0xf6cc7ffd6bb67292ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control_tcp/ClearErrorResponse";
  }

  static const char* value(const ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 res\n"
;
  }

  static const char* value(const ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClearErrorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control_tcp::ClearErrorResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<int32_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_TCP_MESSAGE_CLEARERRORRESPONSE_H
