// Generated by gencpp from file arm_control_tcp/DisableRobot.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_TCP_MESSAGE_DISABLEROBOT_H
#define ARM_CONTROL_TCP_MESSAGE_DISABLEROBOT_H

#include <ros/service_traits.h>


#include <arm_control_tcp/DisableRobotRequest.h>
#include <arm_control_tcp/DisableRobotResponse.h>


namespace arm_control_tcp
{

struct DisableRobot
{

typedef DisableRobotRequest Request;
typedef DisableRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DisableRobot
} // namespace arm_control_tcp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_control_tcp::DisableRobot > {
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::arm_control_tcp::DisableRobot&) { return value(); }
};

template<>
struct DataType< ::arm_control_tcp::DisableRobot > {
  static const char* value()
  {
    return "arm_control_tcp/DisableRobot";
  }

  static const char* value(const ::arm_control_tcp::DisableRobot&) { return value(); }
};


// service_traits::MD5Sum< ::arm_control_tcp::DisableRobotRequest> should match
// service_traits::MD5Sum< ::arm_control_tcp::DisableRobot >
template<>
struct MD5Sum< ::arm_control_tcp::DisableRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_control_tcp::DisableRobot >::value();
  }
  static const char* value(const ::arm_control_tcp::DisableRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_control_tcp::DisableRobotRequest> should match
// service_traits::DataType< ::arm_control_tcp::DisableRobot >
template<>
struct DataType< ::arm_control_tcp::DisableRobotRequest>
{
  static const char* value()
  {
    return DataType< ::arm_control_tcp::DisableRobot >::value();
  }
  static const char* value(const ::arm_control_tcp::DisableRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_control_tcp::DisableRobotResponse> should match
// service_traits::MD5Sum< ::arm_control_tcp::DisableRobot >
template<>
struct MD5Sum< ::arm_control_tcp::DisableRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_control_tcp::DisableRobot >::value();
  }
  static const char* value(const ::arm_control_tcp::DisableRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_control_tcp::DisableRobotResponse> should match
// service_traits::DataType< ::arm_control_tcp::DisableRobot >
template<>
struct DataType< ::arm_control_tcp::DisableRobotResponse>
{
  static const char* value()
  {
    return DataType< ::arm_control_tcp::DisableRobot >::value();
  }
  static const char* value(const ::arm_control_tcp::DisableRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_CONTROL_TCP_MESSAGE_DISABLEROBOT_H
