// Generated by gencpp from file arm_control_tcp/EnableRobotRequest.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_TCP_MESSAGE_ENABLEROBOTREQUEST_H
#define ARM_CONTROL_TCP_MESSAGE_ENABLEROBOTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control_tcp
{
template <class ContainerAllocator>
struct EnableRobotRequest_
{
  typedef EnableRobotRequest_<ContainerAllocator> Type;

  EnableRobotRequest_()
    {
    }
  EnableRobotRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EnableRobotRequest_

typedef ::arm_control_tcp::EnableRobotRequest_<std::allocator<void> > EnableRobotRequest;

typedef boost::shared_ptr< ::arm_control_tcp::EnableRobotRequest > EnableRobotRequestPtr;
typedef boost::shared_ptr< ::arm_control_tcp::EnableRobotRequest const> EnableRobotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace arm_control_tcp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control_tcp/EnableRobotRequest";
  }

  static const char* value(const ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnableRobotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::arm_control_tcp::EnableRobotRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_TCP_MESSAGE_ENABLEROBOTREQUEST_H
