// Generated by gencpp from file arm_control_tcp/ServoJRequest.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_TCP_MESSAGE_SERVOJREQUEST_H
#define ARM_CONTROL_TCP_MESSAGE_SERVOJREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control_tcp
{
template <class ContainerAllocator>
struct ServoJRequest_
{
  typedef ServoJRequest_<ContainerAllocator> Type;

  ServoJRequest_()
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)
    , e(0.0)
    , f(0.0)
    , paramValue()  {
    }
  ServoJRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)
    , e(0.0)
    , f(0.0)
    , paramValue(_alloc)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;

   typedef double _c_type;
  _c_type c;

   typedef double _d_type;
  _d_type d;

   typedef double _e_type;
  _e_type e;

   typedef double _f_type;
  _f_type f;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _paramValue_type;
  _paramValue_type paramValue;





  typedef boost::shared_ptr< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServoJRequest_

typedef ::arm_control_tcp::ServoJRequest_<std::allocator<void> > ServoJRequest;

typedef boost::shared_ptr< ::arm_control_tcp::ServoJRequest > ServoJRequestPtr;
typedef boost::shared_ptr< ::arm_control_tcp::ServoJRequest const> ServoJRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control_tcp::ServoJRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_control_tcp::ServoJRequest_<ContainerAllocator1> & lhs, const ::arm_control_tcp::ServoJRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.d == rhs.d &&
    lhs.e == rhs.e &&
    lhs.f == rhs.f &&
    lhs.paramValue == rhs.paramValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_control_tcp::ServoJRequest_<ContainerAllocator1> & lhs, const ::arm_control_tcp::ServoJRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_control_tcp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6eabb4f33eb0af81449dab9472a3a789";
  }

  static const char* value(const ::arm_control_tcp::ServoJRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6eabb4f33eb0af81ULL;
  static const uint64_t static_value2 = 0x449dab9472a3a789ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control_tcp/ServoJRequest";
  }

  static const char* value(const ::arm_control_tcp::ServoJRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 a\n"
"float64 b\n"
"float64 c\n"
"float64 d\n"
"float64 e\n"
"float64 f\n"
"string[] paramValue\n"
"\n"
;
  }

  static const char* value(const ::arm_control_tcp::ServoJRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.d);
      stream.next(m.e);
      stream.next(m.f);
      stream.next(m.paramValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoJRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control_tcp::ServoJRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control_tcp::ServoJRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
    s << indent << "e: ";
    Printer<double>::stream(s, indent + "  ", v.e);
    s << indent << "f: ";
    Printer<double>::stream(s, indent + "  ", v.f);
    s << indent << "paramValue[]" << std::endl;
    for (size_t i = 0; i < v.paramValue.size(); ++i)
    {
      s << indent << "  paramValue[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.paramValue[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_TCP_MESSAGE_SERVOJREQUEST_H
